
[runa_da_ruina]
	#Raio do campo temporal da runa.
	#Range: 1 ~ 12
	radius = 4
	#Intervalo entre pulsos da runa.
	#Range: 1 ~ 200
	pulseIntervalTicks = 10
	#Random ticks extras em blocos próximos.
	#Range: 0 ~ 64
	extraRandomTicks = 3
	#Tempo ativo por uso.
	#Range: 1 ~ 300
	activeSeconds = 18
	#Carga consumida para ativar a runa.
	#Range: 1 ~ 20000
	activationCost = 240
	#Força de tração sobre criaturas próximas.
	#Range: 0.01 ~ 2.0
	pullStrength = 0.15
	#Carga máxima da runa.
	#Range: 1 ~ 100000
	maxCharge = 2500

[catalisador_magico]
	#Carga máxima do catalisador.
	#Range: 1 ~ 100000
	maxCharge = 12000
	#Carga recebida do céu por pulso.
	#Range: 0 ~ 500
	skyChargePerPulse = 14
	#Carga transferida por pulso para itens próximos.
	#Range: 0 ~ 500
	transferPerPulse = 18
	#Raio de transferência do catalisador.
	#Range: 1 ~ 16
	transferRadius = 5
	#Intervalo de pulso do catalisador.
	#Range: 1 ~ 200
	pulseIntervalTicks = 20

[bateria_arcana]
	#Carga máxima da bateria.
	#Range: 1 ~ 500000
	maxCharge = 40000
	#Carga recebida do céu por pulso.
	#Range: 0 ~ 500
	skyChargePerPulse = 8
	#Carga enviada por pulso.
	#Range: 0 ~ 500
	transferPerPulse = 24
	#Raio de distribuição da bateria.
	#Range: 1 ~ 24
	transferRadius = 6
	#Intervalo de pulso da bateria.
	#Range: 1 ~ 200
	pulseIntervalTicks = 20

[bancada_colheita_arcana]
	#Carga máxima armazenada na bancada.
	#Range: 1 ~ 100000
	maxCharge = 8000
	#Carga puxada de baterias por pulso.
	#Range: 0 ~ 2000
	pullPerPulse = 60
	#Raio para puxar energia das baterias.
	#Range: 1 ~ 32
	batteryRadius = 8
	#Raio de trabalho da bancada.
	#Range: 1 ~ 16
	workRadius = 6
	#Intervalo de pulso da bancada.
	#Range: 1 ~ 200
	pulseIntervalTicks = 20
	#Custo por colheita de planta.
	#Range: 0 ~ 1000
	cropEnergyCost = 16
	#Custo por coleta de carne.
	#Range: 0 ~ 5000
	animalEnergyCost = 70
	#Custo por item teleportado ao baú vinculado.
	#Range: 0 ~ 1000
	teleportEnergyPerItem = 3
	#Máximo de itens teleportados por pulso.
	#Range: 0 ~ 4096
	teleportItemsPerPulse = 16
	#Quantidade mínima de animais adultos por espécie a ser mantida.
	#Range: 0 ~ 16
	animalKeepCount = 2

